name: Build on Linux

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/setup-python@v1.1.1
    - uses: actions/checkout@v1
    - name: bootstrap
      run: ./bootstrap.py
    - name: configure
      run: ./waf configure
    - name: build
      run: ./waf build
