name: Build on Linux

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: docker://registry.cirno.systems/kiwi/containers/mpv-ci:stable-deps
    - uses: actions/checkout@v1
    - name: bootstrap
      run: ./bootstrap.py
    - name: build
      run: ./ci/build-tumbleweed.sh
