name: Build on Linux

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: registry.cirno.systems/kiwi/containers/mpv-ci:stable-deps
    
    steps:
    - uses: actions/checkout@v1
    - name: bootstrap
      run:  python3 ./bootstrap.py
    - name: build
      run: ./ci/build-tumbleweed.sh
